name: VPN MASTER panel
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Выберите действие'
        required: true
        default: 'off'
        type: choice
        options:
        - 'off'
        - 'on'

permissions:
  contents: write

jobs:
  switch_vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update VPN File
        run: |
          if [ "${{ github.event.inputs.action }}" == "off" ]; then
            # Заменяем vless на OFF_vless в файле vpn.txtMASTER
            sed -i 's/vless/OFF_vless/g' vpn.txtMASTER
          else
            # Возвращаем обратно
            sed -i 's/OFF_vless/vless/g' vpn.txtMASTER
          fi
          
      - name: Save changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vpn.txtMASTER
          # Проверяем, есть ли изменения, прежде чем пушить
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "VPN Control: ${{ github.event.inputs.action }}"
            git push
          fi
          
